### ISSUE TITLE
Create ranges

### ISSUE THREAD

**Issue by swo** [CDCgov/pygriddler#31]
People really like linspace and aspace. In an updated schema (see #30 ), have some special keys like `_linspace` or something, that trigger the generation of ranges

**Comment by swo** [comment]
See https://github.com/CDCgov/pygriddler/pull/55#discussion_r2016437565

If you make a range from 0 to 1, and then try to get 0.5, will you actually hit that value?

**Comment by swo** [comment]
I think there's a way this could fit unambiguously into this schema: eg `R0: {vary: [1.5, 2.5]}` and then `R0: {vary: {range: {from: 0.0, to: 1.0, n: 11}}}`. i.e., if the thing after vary: is an array, use those values, but if it's a dict, then it needs to be a dict that makes some other kind of specification, like range

**Comment by swo** [comment]
For even more clarity, this could be that we have a verbose form:

```yaml
my_bundle:
  vary:
    my_param:
      values: [value1, value2]
```

which has the familiar short form:

```yaml
my_param:
  vary:
    [value1, value]
```

but that also allows for different things like ranges:

```yaml
my_param:
  vary:
    range:
      from: 0.0
      to: 1.0
      n: 10
```
