### ISSUE TITLE
Explain in docs that parameter sets can have non-flat values

### ISSUE THREAD

**Issue by swo** [CDCgov/pygriddler#43]
One of the powers of griddler is that the parameters can have values that are not atomic. E.g.:

```yaml
grid_parameters:
  my_dict_valued_parameter:
    - key1: set1_value1
      key2: set1_value2
    - key1: set2_value1
      key2: set2_value2
```

And that will give two parameter sets, the first of which is:

```json
{"my_dict_valued_parameter":
  {
    "key1": "set1_value1",
    "key2": "set1_value2"
  }
}
```

This is why we'll need things like the secret keys like `_range` or `_nest`
