### ISSUE TITLE
Use custom tags?

### ISSUE THREAD

**Issue by swo** [CDCgov/pygriddler#53]
#31 would be solved very well by this:

```yaml
R0: !range {from: 0.5, to: 1.5, n: 11}
```

This would also allow a `!grid` and `!nested_grid` tag so that, rather than stating the types (fixed, grid, nested grid) at the top-level, they would be specified for each parameter:

```yaml
fixed_scalar: "I'm a scalar"
fixed_list: ["I'm", "a", "list"]
grid_of_scalars: !grid [1, 2, 3]
```

The downside is that this means you need YAML input, and you start to veer into DSL territory. Although *any* implementation of this kind of idea is going to be its own DSL; it's just a question of parsing.

This may also relate to #38.
