### ISSUE TITLE
Future schema for complicated nesting

### ISSUE THREAD

**Issue by swo** [CDCgov/pygriddler#65]
@jasonasher had an example that would lead to long-term messiness: Say you wanted run many simulations in which some simulation parameter (I'll just call it $\pi$) was a random variable distribution. The different levels of that simulation parameter would be different distributions and, for each of those distributions, different values of that distribution's parameters.

v0.3 griddler would do this like:

```yaml
parameters:
  pi_dist: {vary: [gamma, negbin]}
  pi_shape:
    if: {equals: {pi_dist: gamma}}
    vary: [0.5, 1.0]
  pi_scale:
    if: {equals: {pi_dist: gamma}}
    vary: [1.0, 2.0]
  pi_mu:
    if: {equals: {pi_dist: negbin}}
    vary: [1.0, 2.0]
  pi_concentration:
    if: {equals: {pi_dist: negbin}}
    vary: [0.1, 1.0, 10.0]
```

This is clearly very tedious. If would also become confusing if you had name collisions. Like, if multiple of the `pi_dist` used `loc` and `scale`, now you'd need to either (1) name them things like `pi_gamma_loc`, `pi_gamma_scale`, etc. or (2) create some more complex if-else logic so that you could make the range of values that `loc` varies over depend on `pi_dist`.

The alternative is to put the distribution at the top level:

```yaml
parameters:
  pi: [
    {
      type: distribution,
      distribution: gamma,
      shape: {vary: [0.5, 1.0]},
      scale: {vary [1.0, 2.0]}
    },
    {
      type: distribution,
      distribution: negbin,
      # etc.
    }
  ]
```

This suggests a world where each of the parameters actually needs to have some type declared, so that you don't need to repeat `type: distribution` for each value of `pi`.

But it also means that griddler would need to know how to reach down into these complex types, vary the sub-parameters `shape` and `scale`, and then flatten that into the output JSONs.
