### ISSUE TITLE
Specify varying bundles as list of objects?

### ISSUE THREAD

**Issue by swo** [CDCgov/pygriddler#66]
In v0.3, we have:

```yaml
parameters:
  scenario:
    vary:
      R0: [1, 2, 3]
      gamma: [1, 2, 3]
```

It would be more verbose but potentially less error prone to have something like:

```yaml
    vary:
      - {R0: 1, gamma: 1}
      - {R0: 2, gamma: 2}
      - {R0: 3, gamma 3}
```

although in this case you would have `parameters["scenario"]["R0"]` rather than just `parameters["R0"]`.

This was a tension present in the old "nested parameters" (see #54 et al.) and relates to the concept of "promoting" parameters into a higher namespace.

See also #65

**Comment by swo** [comment]
See also #67 for an alternative way to solve this

**Comment by swo** [comment]
#68 introduced the `v0.4` schema, which functions this way.

#75 re-introduces the `v0.3` schema, which I think would be:

```yaml
parameters:
  scenario:
    R0: [1, 2, 3]
    gamma: [1, 2, 3]
```
