### ISSUE TITLE
A(nother) new grammar of parameters

### ISSUE THREAD

**Issue by swo** [CDCgov/pygriddler#67]
Consider:
 
- A *parameter* is a tuple of a parameter *name* and parameter *value*.
- A parameter *map* is 0+ name/value pairs (e.g., a JSON object or Python dictionary).
- An *experiment* is a set of parameter maps (e.g., a JSON array or Python list where the order isn't guaranteed).
- There are *operations*:
  - The *union* of two parameter maps (with disjoint sets of parameter names) is another parameter map.
  - The *union* (or, loosely, concatenation) of two experiments is exactly that: the result is another experiment.
  - The (Cartesian) *product* of two experiments is another experiment consisting of unions of all the pairs of combinations of maps from each experiment.

This obviates some parts of the v0.3 conditional logic (at least, the "equals" logic) and also provides for subgrids. E.g., say I want to scan over a large space of probability density functions. I want to try the normal distribution, with many values of mean and SD, and the gamma distribution, with many values of shape and rate, etc. as well as some other parameters:

- Each distribution is an experiment unto itself, i.e., a set of maps like `{distribution_name: normal, mean: 0.0, sd: 1.0}`
- In the top-level experiment, "distribution" is an experiment (not an actual keyword) represented by the union/concatenation of those experiments, so that there is one map per distribution & parameterization
- The distribution experiment gets product'ed with the other subexperiments to make the final experiment

**Comment by swo** [comment]
In the most verbose expression, where an experiment is represented by either:

1. an array that just is the experiment (i.e., array of map objects) or
2. an object that represents an operation (union or product over other experiments)

then we have:

```yaml
version: TBD
experiment:
  # the top-level experiment is a product of two sub-experiments
  - type: product
    elements:
      # the first sub-experiment is the fixed parameters, which is an experiment
      # that is just a single map
      - [{R0: 1.5, gamma: 1.0}]
      # the second sub-experiment represents all the distribution/parameterization
      # combos. we want to union over those.
      - type: union
        elements:
          # the first sub-sub-experiment is for the normal distribution
          # this has two sub-sub-sub-experiments: one for the a fixed name
          # "normal" then a product over means & SDs
          - type: product
            elements:
              - [{distribution: normal}]
              - type: product
                elements:
                  - type: union
                    elements:
                      - type: map
                        map: {mean: 0.0}
                      - type: map
                        map: {mean: 1.0}
                      - type: map
                        map: {mean: 2.0}
                  - type: union
                    elements:
                      - type: map
                        map: {sd: 0.5}
                      - type: map
                        map: {sd: 1.0}
          # then a second sub-sub-experiment for the gamma distribution, which
          # I'll skip for brevity
```

**Comment by swo** [comment]
And here are all the readme griddles, in this alternative syntax, using a `scan` operation:

```yaml
# just R0 fixed. I love that this is... just the output we want
experiment: [{R0: 1.5}]
---
# 2x2 grid
experiment:
  product:
    - scan: {R0: [1.5, 2.0]}
    - scan: {gamma: [1.0, 2.0]}
---
# simple "bundle": the easiest this is to just write this out
experiment:
  - {R0: low, gamma: low}
  - {R0: high, gamma: high}
# it could get its own syntax, like `multiscan` or parallel scan or something,
# but I'm not sure it helps at all, unless you had very many values
experiments:
  parallel_scan:
    R0: [low, high]
    gamma: [low, high]
# the newton vs brent subgrid is the most illustrative
experiment:
  union:
    - {method: brent, lower: 0.0, upper: 1.0}
    - product:
      - [{method: newton}]
      - scan: {start_point: [0.25, 0.50, 0.75]}
```
